/**
 * 
 * Contansts
 * 
 */

const LOAD_MEAL_CATEGORIES = `LOAD_MEAL_CATEGORIES`;
const LOAD_MEAL_CATEGORIES_SUCCESS = `LOAD_MEAL_CATEGORIES_SUCCESS`;
const LOAD_MEAL_CATEGORIES_ERROR = `LOAD_MEAL_CATEGORIES_ERROR`;
const LOAD_MEAL_CATEGORY = `LOAD_MEAL_CATEGORY`;
const LOAD_MEAL_CATEGORY_SUCCESS = `LOAD_MEAL_CATEGORY_SUCCESS`;
const LOAD_MEAL_CATEGORY_ERROR = `LOAD_MEAL_CATEGORY_ERROR`;
const LOAD_MEAL_DETAILS = `LOAD_MEAL_DETAILS`;
const LOAD_MEAL_DETAILS_SUCCESS = `LOAD_MEAL_DETAILS_SUCCESS`;
const LOAD_MEAL_DETAILS_ERROR = `LOAD_MEAL_DETAILS_ERROR`;

const ADD_MEAL_TO_CART = `ADD_MEAL_TO_CART`;
const REMOVE_MEAL_FROM_CART = `REMOVE_MEAL_FROM_CART`;

const PLACE_ORDER = `PLACE_ORDER`;
const PLACE_ORDER_SUCCESS = `PLACE_ORDER_SUCCESS`;
const PLACE_ORDER_ERROR = `PLACE_ORDER_ERROR`;


export {
    LOAD_MEAL_CATEGORIES,
    LOAD_MEAL_CATEGORIES_SUCCESS,
    LOAD_MEAL_CATEGORIES_ERROR,
    LOAD_MEAL_CATEGORY,
    LOAD_MEAL_CATEGORY_SUCCESS,
    LOAD_MEAL_CATEGORY_ERROR,
    LOAD_MEAL_DETAILS,
    LOAD_MEAL_DETAILS_SUCCESS,
    LOAD_MEAL_DETAILS_ERROR,
    ADD_MEAL_TO_CART,
    REMOVE_MEAL_FROM_CART,
    PLACE_ORDER,
    PLACE_ORDER_SUCCESS,
    PLACE_ORDER_ERROR
}